- hosts: manager
  become: true
  tasks:
  - name: Copy docker-compose
    copy:
      src: docker-compose.yaml
      dest: docker-compose.yaml

- hosts: nginxloadbalancer
  become: true
  roles:
  - loadbalancer