- hosts: all
  become: true
  roles:
  - install_docker

- hosts: manager
  become: true
  roles:
  - docker_manager

- hosts: worker
  become: true
  roles:
  - docker_worker

- hosts: nginx
  become: true
  roles:
  - loadbalancer